# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: BEC4
# email: bec4@mit.edu
description: >- # this means to ignore newlines until "baseurl:"
  Homepage of the BEC4 lab at MIT.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bec4.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
# theme: alembic-jekyll-theme
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-commonmark
  - jemoji

remote_theme: daviddarnes/alembic@main

# 4. Jekyll settings
# sass:
  # style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)

# 6. Site wide defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout

  - scope:
      path: ""
      type: posts
    values:
      layout: post

  - scope:
      path: ""
      type: tag
    values:
      layout: tag
collections:
  tag:
      output: true

navigation_header:
  - title: Home
    url: /
  - title: Science
    url: /science/
  - title: Contact
    url: /contact/
  - title: Team
    url: /team/

navigation_footer:
  - title: BEC4
    url: /

fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
